## Question 2 Horse racing tips classification

## Team Members
Dhrish S Kumar - E0320008<br>
A Ch Rohit - E0320022<br><br>
Dataset - Horse racing tips

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("tips.csv")
df.head()

UID  ID    Tipster        Date      Track              Horse Bet Type  \
0    1   1  Tipster A  24/07/2015      Ascot          Fredricka      Win   
1    2   2  Tipster A  24/07/2015     Thirsk      Spend A Penny      Win   
2    3   3  Tipster A  24/07/2015       York  Straightothepoint      Win   
3    4   4  Tipster A  24/07/2015  Newmarket     Miss Inga Sock      Win   
4    5   5  Tipster A  25/07/2015      Ascot              Peril      Win   

   Odds Result  TipsterActive  
0  8.00   Lose           True  
1  4.50   Lose           True  
2  7.00   Lose           True  
3  5.00   Lose           True  
4  4.33    Win           True

In [3]:
df.shape

(38248, 10)

## Data Cleaning and Data Preparation

In [4]:
df.describe()

UID            ID          Odds
count  38248.000000  38248.000000  38248.000000
mean   19124.500000   1013.308251     10.994968
std    11041.390885    917.941098     11.004589
min        1.000000      1.000000      1.070000
25%     9562.750000    318.000000      5.000000
50%    19124.500000    749.000000      8.000000
75%    28686.250000   1419.000000     13.000000
max    38248.000000   4383.000000    407.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38248 entries, 0 to 38247
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   UID            38248 non-null  int64  
 1   ID             38248 non-null  int64  
 2   Tipster        38248 non-null  object 
 3   Date           38248 non-null  object 
 4   Track          38248 non-null  object 
 5   Horse          38248 non-null  object 
 6   Bet Type       38248 non-null  object 
 7   Odds           38248 non-null  float64
 8   Result         38248 non-null  object 
 9   TipsterActive  38248 non-null  bool   
dtypes: bool(1), float64(1), int64(2), object(6)
memory usage: 2.7+ MB


In [6]:
df.isna().any()

UID              False
ID               False
Tipster          False
Date             False
Track            False
Horse            False
Bet Type         False
Odds             False
Result           False
TipsterActive    False
dtype: bool

In [7]:
x=df.iloc[:,[2,3,4,5,6,7,9]]
y=df.iloc[:,8:9]
x

Tipster        Date      Track              Horse  Bet Type   Odds  \
0       Tipster A  24/07/2015      Ascot          Fredricka       Win   8.00   
1       Tipster A  24/07/2015     Thirsk      Spend A Penny       Win   4.50   
2       Tipster A  24/07/2015       York  Straightothepoint       Win   7.00   
3       Tipster A  24/07/2015  Newmarket     Miss Inga Sock       Win   5.00   
4       Tipster A  25/07/2015      Ascot              Peril       Win   4.33   
...           ...         ...        ...                ...       ...    ...   
38243  Tipster E1  02/04/2016    Kempton        Solar Flair       Win   7.00   
38244  Tipster E1  02/04/2016  Doncaster    Express Himself  Each Way  12.00   
38245  Tipster E1  02/04/2016  Doncaster        Jack Dexter       Win   7.00   
38246  Tipster E1  02/04/2016      Kelso       Just Cameron       Win   4.33   
38247  Tipster E1  31/05/2016     Redcar         Dream Farr       Win   5.00   

       TipsterActive  
0               True  
1               True  
2               True  
3               True  
4               True  
...              ...  
38243          False  
38244          False  
38245          False  
38246          False  
38247          False  

[38248 rows x 7 columns]

In [8]:
y

Result
0       Lose
1       Lose
2       Lose
3       Lose
4        Win
...      ...
38243   Lose
38244   Lose
38245   Lose
38246   Lose
38247   Lose

[38248 rows x 1 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
columns=["Tipster","Date","Track","Horse","Bet Type","TipsterActive"]
for col in columns:
    x[col]=le.fit_transform(x[col])
x.head()

<ipython-input-9-91da4de41028>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[col]=le.fit_transform(x[col])


Tipster  Date  Track  Horse  Bet Type  Odds  TipsterActive
0        0   818      2   5157         1  8.00              1
1        0   818     96  13103         1  4.50              1
2        0   818    114  13406         1  7.00              1
3        0   818     74   8974         1  5.00              1
4        0   851      2  10550         1  4.33              1

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y=pd.DataFrame(y,columns=["Result"])
y.head()

C:\Users\Rohit Anand\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Result
0       0
1       0
2       0
3       0
4       1

In [11]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
scaled_x=ss.fit_transform(x)
scaled_x=pd.DataFrame(scaled_x,columns=x.columns)

## Data Splitting

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(scaled_x,y,test_size=0.30,random_state=0)

## Building Models

**Logisitc Regression Model**

In [13]:
from sklearn.linear_model import LogisticRegression 
log=LogisticRegression()
log.fit(x_train,y_train)
log_pred=log.predict(x_test)
log_pred=log_pred.reshape(len(log_pred),1)
log_predicted=pd.DataFrame(log_pred,columns=['Predicted'])
log_predicted

C:\Users\Rohit Anand\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Predicted
0              0
1              0
2              0
3              0
4              0
...          ...
11470          0
11471          0
11472          0
11473          0
11474          0

[11475 rows x 1 columns]

**KNN (K Nearest Neighbors) Model**

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn.fit(x_train,y_train)
knn_pred=knn.predict(x_test)
knn_pred

C:\Users\Rohit Anand\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([0, 0, 1, ..., 0, 1, 0])

**Decision Tree Model**

In [16]:
from sklearn.tree import DecisionTreeClassifier
decision_tree=DecisionTreeClassifier(criterion='entropy',random_state=0)
decision_tree.fit(x_train,y_train)
dt_pred=decision_tree.predict(x_test)
print(dt_pred)
print(np.concatenate((dt_pred.reshape(-1,1),np.array(y_test).reshape(-1,1)),1))

[0 0 1 ... 0 1 0]
[[0 0]
 [0 0]
 [1 0]
 ...
 [0 0]
 [1 0]
 [0 1]]


**Naive Bayes Model**

In [17]:
from sklearn.naive_bayes import GaussianNB
NB = GaussianNB()
NB.fit(x_train, y_train)
NB_pred = NB.predict(x_test)
NB_pred

C:\Users\Rohit Anand\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([0, 0, 0, ..., 0, 0, 0])

## Performance Evaluation
**Calculating and displaying classification report, confusion report, accuracy for <br>
Logistic Regression model** 

In [18]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
log_cr=classification_report(y_test,log_pred)
log_conf=confusion_matrix(y_test,log_pred)
log_ac=accuracy_score(y_test,log_pred)
print("\t\tLogistic Regression's Classification Report\n\n",log_cr)
print("\t\tLogistic Regression's Confusion Matrix\n\n",log_conf)
print("\nLogistic Regression's Accuracy Score is ",log_ac)

		Logistic Regression's Classification Report

               precision    recall  f1-score   support

           0       0.81      1.00      0.89      9237
           1       0.52      0.01      0.01      2238

    accuracy                           0.81     11475
   macro avg       0.66      0.50      0.45     11475
weighted avg       0.75      0.81      0.72     11475

		Logistic Regression's Confusion Matrix

 [[9222   15]
 [2222   16]]

Logistic Regression's Accuracy Score is  0.8050544662309368


**Calculating and displaying classification report, confusion report, accuracy for <br>
KNN Classification model** 

In [19]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
knn_cr=classification_report(y_test,knn_pred)
knn_conf=confusion_matrix(y_test,knn_pred)
knn_ac=accuracy_score(y_test,knn_pred)
print("\t\tKNN's Classification Report\n\n",knn_cr)
print("\t\tKNN's Confusion Matrix\n\n",knn_conf)
print("\nKNN's Accuracy Score is ",knn_ac)

		KNN's Classification Report

               precision    recall  f1-score   support

           0       0.82      0.92      0.87      9237
           1       0.30      0.14      0.19      2238

    accuracy                           0.77     11475
   macro avg       0.56      0.53      0.53     11475
weighted avg       0.72      0.77      0.73     11475

		KNN's Confusion Matrix

 [[8538  699]
 [1934  304]]

KNN's Accuracy Score is  0.7705446623093682


**Calculating and displaying classification report, confusion report, accuracy for <br>
Decision Tree Classification model** 

In [20]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
dt_cr=classification_report(y_test,dt_pred)
dt_conf=confusion_matrix(y_test,dt_pred)
dt_ac=accuracy_score(y_test,dt_pred)
print("\t\tDecision Tree's Classification Report\n\n",dt_cr)
print("\t\tDecision Tree's  Confusion Matrix\n\n",dt_conf)
print("\nDecision Tree's Accuracy Score is ",dt_ac)

		Decision Tree's Classification Report

               precision    recall  f1-score   support

           0       0.83      0.81      0.82      9237
           1       0.29      0.31      0.30      2238

    accuracy                           0.71     11475
   macro avg       0.56      0.56      0.56     11475
weighted avg       0.72      0.71      0.72     11475

		Decision Tree's  Confusion Matrix

 [[7493 1744]
 [1539  699]]

Decision Tree's Accuracy Score is  0.7138997821350762


**Calculating and displaying classification report, confusion report, accuracy for <br>
Naive Bayes Classification model** 

In [21]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
NB_cr=classification_report(y_test,NB_pred)
NB_conf=confusion_matrix(y_test,NB_pred)
NB_ac=accuracy_score(y_test,NB_pred)
print("\t\tNaive Bayes's Classification Report\n\n",NB_cr)
print("\t\tNaive Bayes's  Confusion Matrix\n\n",NB_conf)
print("\nNaive Bayes's Accuracy Score is ",NB_ac)

		Naive Bayes's Classification Report

               precision    recall  f1-score   support

           0       0.81      1.00      0.89      9237
           1       0.41      0.01      0.02      2238

    accuracy                           0.80     11475
   macro avg       0.61      0.50      0.46     11475
weighted avg       0.73      0.80      0.72     11475

		Naive Bayes's  Confusion Matrix

 [[9200   37]
 [2212   26]]

Naive Bayes's Accuracy Score is  0.8040087145969499
